"""
Base Strategy — abstract base class for all trading strategies.

Defines the interface and common functionality that all strategy
implementations must follow. Provides signal data structures and
utility methods for technical indicator calculations.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Attributes:
        symbol: Trading symbol (e.g., "BTC/USDT").
        side: Signal direction ("BUY" or "SELL").
        strategy_name: Name of the strategy that generated the signal.
        confidence: Signal confidence score (0.0 to 1.0).
        entry_price: Suggested entry price.
        stop_loss: Suggested stop loss price.
        take_profit: Suggested take profit price.
        signal_type: Type of signal ("ENTRY", "EXIT", "REVERSAL").
        timestamp: When the signal was generated.
        timeframe: Timeframe of the analysis.
        metadata: Additional strategy-specific data.
    """

    symbol: str
    side: str  # "BUY" or "SELL"
    strategy_name: str
    confidence: float = 0.5
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    signal_type: str = "ENTRY"  # "ENTRY", "EXIT", "REVERSAL"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    timeframe: str = "1h"
    metadata: Dict[str, Any] = field(default_factory=dict)
    id: Optional[str] = None

    def __post_init__(self) -> None:
        """Validate signal fields after initialization."""
        if self.side not in ("BUY", "SELL"):
            raise ValueError(f"Signal side must be BUY or SELL, got '{self.side}'")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be 0-1, got {self.confidence}")
        if self.signal_type not in ("ENTRY", "EXIT", "REVERSAL"):
            raise ValueError(f"Signal type must be ENTRY, EXIT, or REVERSAL, got '{self.signal_type}'")

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "id": self.id,
            "symbol": self.symbol,
            "side": self.side,
            "strategy_name": self.strategy_name,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "signal_type": self.signal_type,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "timeframe": self.timeframe,
            "metadata": self.metadata,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategy implementations must inherit from this class and
    implement the required abstract methods.

    Attributes:
        name: Human-readable strategy name.
        strategy_id: Unique strategy identifier (from database).
        timeframe: Default analysis timeframe.
        is_active: Whether the strategy is currently active.
        parameters: Strategy-specific parameters.
    """

    def __init__(
        self,
        name: str = "Base Strategy",
        strategy_id: Optional[str] = None,
        timeframe: str = "1h",
        is_active: bool = True,
        **kwargs: Any,
    ) -> None:
        """
        Initialize the base strategy.

        Args:
            name: Strategy display name.
            strategy_id: Database strategy ID.
            timeframe: Default candle timeframe.
            is_active: Whether the strategy is active.
            **kwargs: Additional strategy parameters.
        """
        self.name = name
        self.strategy_id = strategy_id
        self.timeframe = timeframe
        self.is_active = is_active
        self.parameters: Dict[str, Any] = kwargs
        self._initialized: bool = False

    async def initialize(self) -> None:
        """
        Initialize the strategy. Called once before signal generation.

        Override to perform one-time setup (loading models, etc.).
        """
        self._initialized = True
        logger.info(f"Strategy '{self.name}' initialized (timeframe={self.timeframe})")

    async def stop(self) -> None:
        """Stop the strategy and clean up resources."""
        self.is_active = False
        logger.info(f"Strategy '{self.name}' stopped")

    # -----------------------------------------------------------------------
    # Abstract Methods
    # -----------------------------------------------------------------------

    @abstractmethod
    async def calculate_signals(
        self,
        symbol: str,
        data: List[List[float]],
    ) -> List[Signal]:
        """
        Calculate trading signals based on OHLCV data.

        Args:
            symbol: Trading symbol (e.g., "BTC/USDT").
            data: OHLCV data as list of [timestamp, open, high, low, close, volume].

        Returns:
            List of generated Signal objects.
        """
        ...

    # -----------------------------------------------------------------------
    # Optional Override Methods
    # -----------------------------------------------------------------------

    async def on_bar(
        self,
        symbol: str,
        bar: List[float],
    ) -> None:
        """
        Called when a new candle/bar is received.

        Override for stateful strategies that need to process each bar.

        Args:
            symbol: Trading symbol.
            bar: Single candle [timestamp, open, high, low, close, volume].
        """
        pass

    async def should_enter(
        self,
        signal: Signal,
    ) -> bool:
        """
        Additional entry filter. Called after signal generation.

        Override to add custom entry conditions.

        Args:
            signal: The generated signal.

        Returns:
            True if the trade should be entered, False to skip.
        """
        return signal.confidence >= 0.5

    async def should_exit(
        self,
        position: Any,
        data: List[List[float]],
    ) -> bool:
        """
        Check if an open position should be closed.

        Override to implement custom exit logic.

        Args:
            position: The open position to evaluate.
            data: Current OHLCV data.

        Returns:
            True if the position should be closed.
        """
        return False

    def get_stop_loss(
        self,
        entry_price: float,
        side: str,
    ) -> float:
        """
        Calculate stop loss price based on strategy logic.

        Override to implement custom stop loss calculation.

        Args:
            entry_price: Entry price of the trade.
            side: Trade side ("BUY" or "SELL").

        Returns:
            Stop loss price.
        """
        # Default: 1% stop loss
        if side == "BUY":
            return entry_price * 0.99
        else:
            return entry_price * 1.01

    def get_take_profit(
        self,
        entry_price: float,
        side: str,
    ) -> float:
        """
        Calculate take profit price based on strategy logic.

        Override to implement custom take profit calculation.

        Args:
            entry_price: Entry price of the trade.
            side: Trade side ("BUY" or "SELL").

        Returns:
            Take profit price.
        """
        # Default: 2% take profit (1:2 risk/reward)
        if side == "BUY":
            return entry_price * 1.02
        else:
            return entry_price * 0.98

    # -----------------------------------------------------------------------
    # Utility Methods — Technical Indicators
    # -----------------------------------------------------------------------

    @staticmethod
    def sma(data: np.ndarray, period: int) -> np.ndarray:
        """
        Simple Moving Average.

        Args:
            data: Array of price values.
            period: SMA period.

        Returns:
            Array of SMA values (NaN for insufficient data).
        """
        if len(data) < period:
            return np.full_like(data, np.nan, dtype=float)
        weights = np.ones(period) / period
        return np.convolve(data, weights, mode="valid")

    @staticmethod
    def ema(data: np.ndarray, period: int) -> np.ndarray:
        """
        Exponential Moving Average.

        Args:
            data: Array of price values.
            period: EMA period.

        Returns:
            Array of EMA values.
        """
        if len(data) < period:
            return np.full_like(data, np.nan, dtype=float)
        result = np.zeros_like(data, dtype=float)
        multiplier = 2.0 / (period + 1)

        # Initialize with SMA
        result[period - 1] = np.mean(data[:period])
        for i in range(period, len(data)):
            result[i] = (data[i] - result[i - 1]) * multiplier + result[i - 1]

        result[:period - 1] = np.nan
        return result

    @staticmethod
    def rsi(data: np.ndarray, period: int = 14) -> np.ndarray:
        """
        Relative Strength Index.

        Args:
            data: Array of closing prices.
            period: RSI period.

        Returns:
            Array of RSI values.
        """
        if len(data) < period + 1:
            return np.full_like(data, np.nan, dtype=float)

        deltas = np.diff(data)
        result = np.full_like(data, np.nan, dtype=float)

        gains = np.where(deltas > 0, deltas, 0)
        losses = np.where(deltas < 0, -deltas, 0)

        avg_gain = np.mean(gains[:period])
        avg_loss = np.mean(losses[:period])

        if avg_loss == 0:
            result[period] = 100.0
        else:
            rs = avg_gain / avg_loss
            result[period] = 100 - (100 / (1 + rs))

        for i in range(period, len(deltas)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period

            if avg_loss == 0:
                result[i + 1] = 100.0
            else:
                rs = avg_gain / avg_loss
                result[i + 1] = 100 - (100 / (1 + rs))

        return result

    @staticmethod
    def macd(
        data: np.ndarray,
        fast: int = 12,
        slow: int = 26,
        signal_period: int = 9,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        MACD (Moving Average Convergence Divergence).

        Args:
            data: Array of closing prices.
            fast: Fast EMA period.
            slow: Slow EMA period.
            signal_period: Signal line period.

        Returns:
            Tuple of (macd_line, signal_line, histogram).
        """
        ema_fast = BaseStrategy.ema(data, fast)
        ema_slow = BaseStrategy.ema(data, slow)

        macd_line = ema_fast - ema_slow
        valid_mask = ~np.isnan(macd_line)
        macd_valid = macd_line[valid_mask]

        if len(macd_valid) < signal_period:
            return (
                np.full_like(data, np.nan, dtype=float),
                np.full_like(data, np.nan, dtype=float),
                np.full_like(data, np.nan, dtype=float),
            )

        signal_line = BaseStrategy.ema(macd_valid, signal_period)
        histogram = macd_valid - signal_line

        # Pad to original length
        macd_result = np.full_like(data, np.nan, dtype=float)
        signal_result = np.full_like(data, np.nan, dtype=float)
        hist_result = np.full_like(data, np.nan, dtype=float)

        valid_indices = np.where(valid_mask)[0]
        offset = len(valid_indices) - len(signal_line)
        for i, idx in enumerate(valid_indices):
            macd_result[idx] = macd_valid[i]
            if i >= offset:
                signal_result[idx] = signal_line[i - offset]
                hist_result[idx] = histogram[i - offset]

        return macd_result, signal_result, hist_result

    @staticmethod
    def bollinger_bands(
        data: np.ndarray,
        period: int = 20,
        std_dev: float = 2.0,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Bollinger Bands.

        Args:
            data: Array of closing prices.
            period: Moving average period.
            std_dev: Number of standard deviations.

        Returns:
            Tuple of (upper_band, middle_band, lower_band).
        """
        if len(data) < period:
            nan_arr = np.full_like(data, np.nan, dtype=float)
            return nan_arr, nan_arr, nan_arr

        middle = np.zeros_like(data, dtype=float)
        upper = np.zeros_like(data, dtype=float)
        lower = np.zeros_like(data, dtype=float)

        for i in range(period - 1, len(data)):
            window = data[i - period + 1 : i + 1]
            middle[i] = np.mean(window)
            std = np.std(window, ddof=0)
            upper[i] = middle[i] + std_dev * std
            lower[i] = middle[i] - std_dev * std

        middle[:period - 1] = np.nan
        upper[:period - 1] = np.nan
        lower[:period - 1] = np.nan

        return upper, middle, lower

    @staticmethod
    def atr(
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
        period: int = 14,
    ) -> np.ndarray:
        """
        Average True Range.

        Args:
            high: Array of high prices.
            low: Array of low prices.
            close: Array of closing prices.
            period: ATR period.

        Returns:
            Array of ATR values.
        """
        if len(close) < 2:
            return np.full_like(close, np.nan, dtype=float)

        true_range = np.zeros(len(close), dtype=float)
        true_range[0] = high[0] - low[0]

        for i in range(1, len(close)):
            tr1 = high[i] - low[i]
            tr2 = abs(high[i] - close[i - 1])
            tr3 = abs(low[i] - close[i - 1])
            true_range[i] = max(tr1, tr2, tr3)

        if len(true_range) < period:
            return np.full_like(close, np.nan, dtype=float)

        atr_values = np.full_like(close, np.nan, dtype=float)
        atr_values[period - 1] = np.mean(true_range[:period])

        multiplier = 1.0 / period
        for i in range(period, len(close)):
            atr_values[i] = atr_values[i - 1] * (1 - multiplier) + true_range[i] * multiplier

        return atr_values

    @staticmethod
    def extract_ohlcv(data: List[List[float]]) -> tuple[np.ndarray, ...]:
        """
        Extract OHLCV arrays from raw data.

        Args:
            data: List of [timestamp, open, high, low, close, volume].

        Returns:
            Tuple of (timestamps, open, high, low, close, volume) as numpy arrays.
        """
        arr = np.array(data, dtype=float)
        if arr.size == 0:
            empty = np.array([], dtype=float)
            return empty, empty, empty, empty, empty, empty
        return (
            arr[:, 0],  # timestamps
            arr[:, 1],  # open
            arr[:, 2],  # high
            arr[:, 3],  # low
            arr[:, 4],  # close
            arr[:, 5],  # volume
        )

    @staticmethod
    def volume_sma(volume: np.ndarray, period: int = 20) -> np.ndarray:
        """
        Simple Moving Average of volume.

        Args:
            volume: Array of volume values.
            period: SMA period.

        Returns:
            Array of volume SMA values.
        """
        return BaseStrategy.sma(volume, period)
